version: '3.8'

services:
  web:
    build: 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/webproject
    networks:
      - main_line

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - main_line
volumes:
  mongo-data:


networks:
  main_line:   # Define your custom network here
    driver: bridge