version: '3.8'

services:
  mongo:
    image: docker.io/mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  express-server:
    image: docker.io/alpine:latest
    container_name: express-server
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "./start-express.sh"
    # depends_on:
    #   - mongo
    # environment:
    #   MONGO_URI: mongodb://root:example@mongo:27017

  react-app:
    image: docker.io/alpine:latest
    container_name: react-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "5173:5173"
    command: sh -c "./start-react.sh"
    # depends_on:
    #   - express-server

volumes:
  mongo-data:
    driver: local
